name: Run action

on:
  workflow_dispatch:
    inputs:
      comment:
        description: 'Comment'
        required: true

jobs:
    blah:
        runs-on: ubuntu-20.04

        strategy:
            fail-fast: true

        steps:
            # - name: Print context
            #   run: echo ${{ toJson(github) }}
            - name: Use python
              env:
                HELLO: $(python -c 'print("hello there")')
              run: echo $HELLO
            - name: Print branch
              run: echo ${{ github.ref_name }}
            - name: Print user
              run: echo ${{ github.actor }}
            - name: Print comment
              run: echo ${{ github.event.inputs.comment }}
